### ISSUE TITLE
Error: Match error: Expected string, got undefined in field email

### ISSUE THREAD

**Issue by samurai-jack** [sys13/perzenel#3]
Hi. Before starting the application done steps 1 - 6 and I wanted to run the command "meteor" but when you run the application error occurred:

I20150810-05:36:31.161(0)? adding user fixtures
I20150810-05:36:31.163(0)? {}
W20150810-05:36:31.164(0)? (STDERR)
W20150810-05:36:31.164(0)? (STDERR) /home/vagrant/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150810-05:36:31.164(0)? (STDERR)                                             throw(ex);
W20150810-05:36:31.165(0)? (STDERR)                                                   ^
W20150810-05:36:31.165(0)? (STDERR) Error: Match error: Expected string, got undefined in field email
W20150810-05:36:31.165(0)? (STDERR)     at checkSubtree (packages/check/match.js:159:1)
W20150810-05:36:31.165(0)? (STDERR)     at packages/check/match.js:296:1
W20150810-05:36:31.165(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20150810-05:36:31.166(0)? (STDERR)     at checkSubtree (packages/check/match.js:290:1)
W20150810-05:36:31.166(0)? (STDERR)     at check (packages/check/match.js:32:1)
W20150810-05:36:31.166(0)? (STDERR)     at createUser (packages/accounts-password/password_server.js:696:1)
W20150810-05:36:31.166(0)? (STDERR)     at Object.Accounts.createUser (packages/accounts-password/password_server.js:776:1)
W20150810-05:36:31.167(0)? (STDERR)     at app/server/fixtures.js:23:23
W20150810-05:36:31.167(0)? (STDERR)     at Array.forEach (native)
W20150810-05:36:31.167(0)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
=> Exited with code: 8

Where I made a mistake when starting the application.

**Comment by sys13** [comment]
@samurai-jack Try running 'meteor --settings setttings_dev.json'. I'll add this to the docs!

**Comment by sys13** [comment]
@samurai-jack What I think was happening was it was running the fixtures.js file and trying to add the initial user and trying to look up information from the settings file that wasn't being provided. 

Let me know if this fixes this for you!

**Comment by samurai-jack** [comment]
It works great. Thanks for the help
